In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
iris = load_iris()

X = iris.data
y = iris.target

In [3]:
# Use only two classes: Setosa and Versicolor
binary_filter = y < 2

X = X[binary_filter]
y = y[binary_filter]

In [4]:
# Reshape target to column format
y = y.reshape(-1, 1)

# Use only 2 features for the input layer
# sepal length and sepal width
X = X[:, :2]

In [5]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [7]:
#Activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(output):
    return output * (1 - output)

In [8]:
#Initialize Neural Networks
np.random.seed(42)

input_neurons = 2
hidden_neurons = 4
output_neurons = 1

learning_rate = 0.1
epochs = 5000

W1 = np.random.randn(input_neurons, hidden_neurons)
b1 = np.zeros((1, hidden_neurons))

W2 = np.random.randn(hidden_neurons, output_neurons)
b2 = np.zeros((1, output_neurons))

print("Model Structure:")
print("Input layer:", input_neurons, "features")
print("Hidden layer:", hidden_neurons, "neurons")
print("Output layer:", output_neurons, "neuron")
print("Dataset: Iris binary classification")
print("Classes: Setosa = 0, Versicolor = 1")
print()

Model Structure:
Input layer: 2 features
Hidden layer: 4 neurons
Output layer: 1 neuron
Dataset: Iris binary classification
Classes: Setosa = 0, Versicolor = 1



In [10]:
#Training loop
for epoch in range(epochs):

    # Forward pass
    hidden_input = np.dot(X_train, W1) + b1
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, W2) + b2
    y_pred = sigmoid(final_input)

    # Loss calculation: Mean Squared Error
    loss = np.mean((y_train - y_pred) ** 2)

    # Backpropagation
    error = y_train - y_pred

    d_output = error * sigmoid_derivative(y_pred)

    error_hidden = d_output.dot(W2.T)
    d_hidden = error_hidden * sigmoid_derivative(hidden_output)

    # Weight update
    W2 += hidden_output.T.dot(d_output) * learning_rate
    b2 += np.sum(d_output, axis=0, keepdims=True) * learning_rate

    W1 += X_train.T.dot(d_hidden) * learning_rate
    b1 += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate

    # Print loss every 500 epochs
    if epoch % 500 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.6f}")

Epoch 0, Loss: 0.284238
Epoch 500, Loss: 0.000824
Epoch 1000, Loss: 0.000356
Epoch 1500, Loss: 0.000219
Epoch 2000, Loss: 0.000155
Epoch 2500, Loss: 0.000119
Epoch 3000, Loss: 0.000096
Epoch 3500, Loss: 0.000080
Epoch 4000, Loss: 0.000069
Epoch 4500, Loss: 0.000060


In [11]:
#Training Model
hidden_input_test = np.dot(X_test, W1) + b1
hidden_output_test = sigmoid(hidden_input_test)

final_input_test = np.dot(hidden_output_test, W2) + b2
test_predictions = sigmoid(final_input_test)

rounded_predictions = np.round(test_predictions)

print("\nFinal Test Predictions:")
print(test_predictions[:10])

print("\nRounded Predictions:")
print(rounded_predictions[:10])

print("\nActual Values:")
print(y_test[:10])

accuracy = np.mean(rounded_predictions == y_test)

print("\nTest Accuracy:", accuracy)



Final Test Predictions:
[[9.99739584e-01]
 [9.99695636e-01]
 [9.99253969e-01]
 [1.83461449e-03]
 [8.29179505e-04]
 [1.58680523e-03]
 [6.85116531e-04]
 [9.99658177e-01]
 [1.94969335e-03]
 [1.22588162e-03]]

Rounded Predictions:
[[1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]]

Actual Values:
[[1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]]

Test Accuracy: 1.0


In [ ]:
#predict a new flower
